//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Компутир.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC()
        {
            this.Session = new HashSet<Session>();
            this.Program = new HashSet<Program>();
        }
    
        public int PCNumber { get; set; }
        public string PCName { get; set; }
        public decimal PCCost { get; set; }
        public int PCDiscount { get; set; }
        public int PCKeyboardID { get; set; }
        public int PCMouseID { get; set; }
        public int PCMonitorID { get; set; }
        public string PCImagePath { get; set; }
        public string PCDescription { get; set; }
    
        public virtual Keyboard Keyboard { get; set; }
        public virtual Monitor Monitor { get; set; }
        public virtual Mouse Mouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Program { get; set; }
    }
}
