//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Компутир.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int SessionID { get; set; }
        public int SessionUser { get; set; }
        public int SessionPC { get; set; }
        public System.DateTime SessionStartDateTime { get; set; }
        public System.DateTime SessionEndDateTime { get; set; }
        public int SessionStatus { get; set; }
        public string SessionComment { get; set; }
    
        public virtual PC PC { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
